const types = {
    DELETE_IMG_DATA:"DELETE_IMG_DATA",
    ADD_IMG_DATA:"ADD_IMG_DATA",
    ADD_IMG_COUNTRIE:"ADD_IMG_COUNTRIE",
    CREATE_ROW:"CREATE_ROW",
    DELETE_ROW:"DELETE_ROW",
    ADD_IMG_ROW:"ADD_IMG_ROW",
    DELETE_IMG_ROW:"DELETE_IMG_ROW",
}
export default types;